# Generated by Django 5.2.6 on 2025-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_cliente_telefone_fixo_alter_cliente_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rede_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(blank=True, choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1, null=True),
        ),
    ]
