# Generated by Django 5.2.6 on 2025-09-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_cliente_data_nascimento_cliente_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eh_cliente', models.BooleanField(default=True)),
                ('eh_fornecedor', models.BooleanField(default=False)),
                ('nome_razao_social', models.CharField(max_length=200)),
                ('tipo_pessoa', models.CharField(blank=True, choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1, null=True)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('rede_social', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_fixo', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('tipo_item', models.CharField(choices=[('P', 'Produto'), ('S', 'Serviço')], default='P', max_length=1, verbose_name='Tipo do Item')),
                ('codigo_sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código (SKU)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('pode_ser_vendido', models.BooleanField(default=True)),
                ('pode_ser_comprado', models.BooleanField(default=False)),
                ('controla_estoque', models.BooleanField(default=True)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo')),
                ('estoque_atual', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Estoque Mínimo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('fornecedor_padrao', models.ForeignKey(blank=True, limit_choices_to={'eh_fornecedor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.contato', verbose_name='Fornecedor Padrão')),
            ],
        ),
        migrations.CreateModel(
            name='PrecoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Venda')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='gestao.item')),
                ('tabela_de_preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.tabeladepreco')),
            ],
            options={
                'unique_together': {('item', 'tabela_de_preco')},
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
