# Generated by Django 5.2.6 on 2025-09-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_contato_item_precoitem_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Grupo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fornecedor_padrao',
        ),
        migrations.AddField(
            model_name='item',
            name='tamanho_em_gramas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tamanho (g)'),
        ),
        migrations.AlterField(
            model_name='precoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_especificos', to='gestao.item'),
        ),
        migrations.AlterField(
            model_name='precoitem',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Venda (Específico)'),
        ),
        migrations.AddField(
            model_name='item',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.grupo'),
        ),
        migrations.CreateModel(
            name='RegraDePreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_em_gramas', models.IntegerField(verbose_name='Tamanho (g)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Venda')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.grupo')),
                ('tabela_de_preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.tabeladepreco')),
            ],
            options={
                'unique_together': {('grupo', 'tabela_de_preco', 'tamanho_em_gramas')},
            },
        ),
    ]
