# Generated by Django 5.2.6 on 2025-09-17 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_grupo_remove_item_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: 140g, 300g, Pequena, Média', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='tamanho_em_gramas',
        ),
        migrations.AlterUniqueTogether(
            name='regradepreco',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='item',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.tamanho'),
        ),
        migrations.AddField(
            model_name='regradepreco',
            name='tamanho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestao.tamanho'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='regradepreco',
            unique_together={('grupo', 'tabela_de_preco', 'tamanho')},
        ),
        migrations.RemoveField(
            model_name='regradepreco',
            name='tamanho_em_gramas',
        ),
    ]
