# Generated by Django 5.2.6 on 2025-09-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_tamanho_remove_item_tamanho_em_gramas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.PositiveIntegerField(unique=True, verbose_name='Número do Pedido')),
                ('status', models.CharField(choices=[('ORC', 'Orçamento'), ('CNF', 'Confirmado'), ('FAT', 'Faturado'), ('CAN', 'Cancelado')], default='ORC', max_length=3)),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CAR', 'Cartão de Crédito/Débito'), ('DIN', 'Dinheiro'), ('OUT', 'Outro')], max_length=3, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'eh_cliente': True}, on_delete=django.db.models.deletion.PROTECT, to='gestao.contato')),
                ('tabela_de_preco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.tabeladepreco')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(limit_choices_to={'pode_ser_vendido': True}, on_delete=django.db.models.deletion.PROTECT, to='gestao.item')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.pedido')),
            ],
        ),
    ]
