# Generated by Django 5.2.6 on 2025-09-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pedido Pago?'),
        ),
    ]
