# Generated by Django 5.2.6 on 2025-10-16 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_pedido_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Cliente / Fornecedor', 'verbose_name_plural': 'Clientes & Fornecedores'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número do Pedido'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Inscrição Estadual')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Principal')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('rede_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rede Social (Instagram, etc.)')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave PIX')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa Assinante',
                'verbose_name_plural': 'Empresas Assinantes',
            },
        ),
    ]
