# Generated by Django 5.2.6 on 2025-10-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_alter_contato_options_alter_pedido_numero_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('CEL', 'Celular'), ('EMAIL', 'E-mail'), ('ALE', 'Chave Aleatória')], max_length=5, null=True, verbose_name='Tipo de Chave PIX'),
        ),
    ]
