# Generated by Django 5.2.6 on 2025-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_empresa_tipo_chave_pix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Minha Empresa', 'verbose_name_plural': 'Minhas Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=200, verbose_name='Nome Fantasia / Nome Completo'),
        ),
    ]
