# Generated by Django 5.2.6 on 2025-10-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0015_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_desconto',
            field=models.CharField(blank=True, choices=[('P', 'Percentual (%)'), ('V', 'Valor Fixo (R$)')], max_length=1, null=True, verbose_name='Tipo de Desconto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto'),
        ),
    ]
