# Generated by Django 5.2.6 on 2025-10-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_pedido_taxa_entrega_pedido_tipo_desconto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='desconto_calculado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Desconto (R$)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_itens',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal dos Itens'),
        ),
    ]
