# Generated by Django 5.2.6 on 2025-10-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_pedido_desconto_calculado_pedido_subtotal_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('tamanho__isnull', False)), fields=('nome', 'tamanho'), name='unique_produto_tamanho'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('tamanho__isnull', True)), fields=('nome',), name='unique_servico_sem_tamanho'),
        ),
    ]
