# Generated by Django 5.2.6 on 2025-10-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0018_alter_item_nome_item_unique_produto_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Em Aberto'), ('F', 'Atendido'), ('C', 'Cancelado')], default='A', max_length=3),
        ),
    ]
