# Generated by Django 5.2.6 on 2025-10-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0019_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='item',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='precoitem',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precos_item', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='regradepreco',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_preco', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='tabeladepreco',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_de_preco', to='gestao.empresa'),
        ),
        migrations.AddField(
            model_name='tamanho',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='gestao.empresa'),
        ),
    ]
