# Generated by Django 5.2.6 on 2025-10-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0020_contato_empresa_grupo_empresa_item_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_produto_tamanho',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_servico_sem_tamanho',
        ),
        migrations.AlterUniqueTogether(
            name='precoitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='regradepreco',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='gestao.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='gestao.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Grupo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código (SKU)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='gestao.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='gestao.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Pedido'),
        ),
        migrations.AlterField(
            model_name='precoitem',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='precos_item', to='gestao.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regradepreco',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_preco', to='gestao.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabeladepreco',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_de_preco', to='gestao.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabeladepreco',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='descricao',
            field=models.CharField(help_text='Ex: 140g, 300g, Pequena, Média', max_length=50),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='gestao.empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='contato',
            unique_together={('empresa', 'cnpj'), ('empresa', 'cpf'), ('empresa', 'inscricao_estadual')},
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together={('empresa', 'numero_pedido')},
        ),
        migrations.AlterUniqueTogether(
            name='precoitem',
            unique_together={('empresa', 'item', 'tabela_de_preco')},
        ),
        migrations.AlterUniqueTogether(
            name='regradepreco',
            unique_together={('empresa', 'grupo', 'tabela_de_preco', 'tamanho')},
        ),
        migrations.AlterUniqueTogether(
            name='tabeladepreco',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='tamanho',
            unique_together={('empresa', 'descricao')},
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('tamanho__isnull', False)), fields=('empresa', 'nome', 'tamanho'), name='unique_produto_tamanho_empresa'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('tamanho__isnull', True)), fields=('empresa', 'nome'), name='unique_servico_sem_tamanho_empresa'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_sku__isnull', False)), fields=('empresa', 'codigo_sku'), name='unique_sku_empresa'),
        ),
    ]
