# Generated by Django 5.2.6 on 2025-10-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0021_remove_item_unique_produto_tamanho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome_beneficiario_pix',
            field=models.CharField(blank=True, help_text='Nome exato que aparece ao receber um PIX nesta chave (máx. 25 caracteres).', max_length=25, null=True, verbose_name='Nome do Beneficiário (PIX)'),
        ),
    ]
