# Generated by Django 5.2.6 on 2025-11-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0022_empresa_nome_beneficiario_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido/Nome da Unidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Atendido'), ('C', 'Cancelado')], default='A', max_length=3),
        ),
    ]
